name: 'Install Conformance Test Client'
description: 'Install and caches the Functions Framework conformance test client'
inputs:
  client-version:
    description: 'Conformance tests client version'
    default: 'latest'
  cache-key:
    description: 'Cache key for storing client'
    default: conformance-client-latest
  cache-path:
    description: 'Filepath where the client is installed'
    default: ~/go/bin/client
runs:
  using: "composite"
  steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.x
    - name: Install client
      run: go install github.com/GoogleCloudPlatform/functions-framework-conformance/client@${INPUTS_CLIENT_VERSION}
      shell: bash
      env:
        INPUTS_CLIENT_VERSION: ${{ inputs.client-version }}
    - name: Move client to cache-path
      # 'mv' fails if the src and dest path are the same, so move it to a temp first just in case
      run: mv ~/go/bin/client /tmp/client && mv /tmp/client ${INPUTS_CACHE_PATH}
      shell: bash
      env:
        INPUTS_CACHE_PATH: ${{ inputs.cache-path }}
    - name: Cache client
      uses: actions/cache@v4
      with:
        path: ${{ inputs.cache-path }}
        key: ${{ inputs.cache-key }}
