name: 'Install Conformance Test Client'
description: 'Install and caches the Functions Framework conformance test client'
inputs:
  client-version:
    description: 'Conformance tests client version'
    default: 'latest'
  cache-key:
    description: 'Cache key for storing client'
    default: conformance-client-latest
runs:
  using: "composite"
  steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.x
    - name: Install client
      run: go install github.com/GoogleCloudPlatform/functions-framework-conformance/client@${{ inputs.client-version }}
      shell: bash
    - name: Cache client
      uses: actions/cache@v3
      with:
        path: ~/go/bin/client
        key: ${{ inputs.cache-key }}