name: 'Run conformance tests'
description: 'Run the functions framework conformance tests with specified parameters.'
inputs:
  cmd:
    description: 'command to run'
    default: ''
  functionType:
    description: 'type of function'
    default: 'http'
  validateMapping:
    description: 'whether to validate mapping from legacy->cloud event and vice versa'
    default: true
runs:
  using: 'node12'
  main: 'index.js'
