language: go

go:
- 1.14

env:
- GO111MODULE=on

go_import_path: github.com/GoogleCloudPlatform/functions-framework-conformance

before_script: go mod vendor

script:
- go test -v ./...
- go vet ./...
- find . -not \( \( -wholename './.git' -o -wholename '*/vendor/*' \) -prune \) -name '*.go' | xargs gofmt -s -d

