name: 'Get Version of Latest Conformance Test Client'
description: 'Returns the latest version of the conformance test client'
outputs:
  version:
    description: version of latest conformance test client
    value: ${{ steps.resolve-latest-client.outputs.version }}
runs:
  using: "composite"
  steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.x
    - name: Resolve latest conformance test client version
      id: resolve-latest-client
      run: |
        VERSION=$(go list -m -json github.com/GoogleCloudPlatform/functions-framework-conformance@latest | jq -r '.Version')
        if [ "$VERSION" = "null" ] || [ -z "$VERSION" ]; then
          echo "Failed to resolve latest version"
          exit 1
        fi
        echo "version=$VERSION" >> $GITHUB_OUTPUT
      shell: bash
